services:
  - type: web
    name: flash-francais-api
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      cp .env.production .env
    startCommand: python /opt/render/project/src/backend/app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flash-francais-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        sync: false
      - key: PORT
        value: 10000

databases:
  - name: flash-francais-db
    databaseName: flash_francais
    plan: free
