services:
  - type: web
    name: flash-francais-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flash-francais-db
          property: connectionString
      - key: ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: BACKEND_CORS_ORIGINS
        value: '["https://flash-francais.onrender.com"]'
      - key: DOCS_URL
        value: /docs
      - key: REDOC_URL
        value: /redoc
      - key: OPENAPI_URL
        value: /openapi.json
      - key: SECRET_KEY
        sync: false

databases:
  - name: flash-francais-db
    databaseName: flash_francais
    plan: free
