services:
  - type: web
    name: flash-francais-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt && cd ..
    startCommand: cd backend && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flash-francais-db
          property: connectionString
      - key: ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: BACKEND_CORS_ORIGINS
        value: '["https://flash-francais.onrender.com"]'
      - key: DOCS_URL
        value: /docs
      - key: REDOC_URL
        value: /redoc
      - key: OPENAPI_URL
        value: /openapi.json
      # Variables secrètes à configurer dans l'interface Render
      - key: SECRET_KEY
        sync: false  # Cette variable devra être configurée manuellement dans l'interface

databases:
  - name: flash-francais-db
    databaseName: flash_francais
    plan: free
