"""Add progressions table

Revision ID: 88dea773a2ba
Revises: c9e9d24c1832
Create Date: 2025-04-01 18:12:29.382265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88dea773a2ba'
down_revision: Union[str, None] = 'c9e9d24c1832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progressions_id'), 'progressions', ['id'], unique=False)
    op.drop_index('ix_flashcards_id', table_name='flashcards')
    op.drop_table('flashcards')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('french_word', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('english_translation', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('example_sentence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='flashcards_pkey')
    )
    op.create_index('ix_flashcards_id', 'flashcards', ['id'], unique=False)
    op.drop_index(op.f('ix_progressions_id'), table_name='progressions')
    op.drop_table('progressions')
    # ### end Alembic commands ###
