"""Ajout du champ difficulty

Revision ID: c9e9d24c1832
Revises: 0d57a6048d02
Create Date: 2025-03-28 15:22:19.311533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e9d24c1832'
down_revision: Union[str, None] = '0d57a6048d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('difficulty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcards', 'difficulty')
    # ### end Alembic commands ###
